### ISSUE TITLE
requires breaks classmethod decorator

### ISSUE THREAD

**Issue by utf** [materialsvirtuallab/monty#112]
Using requires breaks the `@classmethod` decorator.

## System

* Monty version: 3.0.2
* Python version: 3.7
* OS version: Mac OS X

## Summary

* Decorating a class with `monty.dev.requires` breaks the `classmethod` decorator.

## Example code

Working case:
```python
class TestClass:

    @classmethod
    def make_class(cls):
        return cls()

TestClass.make_class()
# Outputs:  <__main__.TestClass at 0x102855210>
```

Now adding `@requires` decorator:
```python
from monty.dev import requires

@requires(True, "msg")
class TestClass:

    @classmethod
    def make_class(cls):
        return cls()

TestClass.make_class()
# Outputs: TypeError: 'classmethod' object is not callable
```

This issue is covered in this blog post: https://hynek.me/articles/decorators/

**Comment by utf** [comment]
I don't know how to fix this bug without introducing additional dependencies into monty. Reversing the use of the decorator only applies when you decorate classmethods directly. I.e. this won't work:

```
from monty.dev import requires

class TestClass:

    @requires(True, "msg")
    @classmethod
    def make_class(cls):
        return cls()
```

But this will:

```
from monty.dev import requires

class TestClass:

    @classmethod
    @requires(True, "msg")
    def make_class(cls):
        return cls()
```

**Comment by mkhorton** [comment]
If a class requires something, I've found putting `@requires` on the `__init__` is better. Having it on the class itself breaks a lot of things, including having the class be MSONable.
