### ISSUE TITLE
Speeding up array serialization

### ISSUE THREAD

**Issue by jakirkham** [materialsvirtuallab/monty#20]
This is related to the issue opened here ( https://github.com/materialsproject/fireworks/issues/97 ). It seemed relevant to raise this here if `monty` plays a role in how `fireworks` performs serialization. There are few relevant points to raise here.

1. Current serialization is too slow, something like `tostring` would be much faster (but less readable).
2. Serialization could be more compact using some form of fast compression. (`blosc` would be worth considering)
3. Large arrays will not fit into a single document in MongoDB. (could use GridFS or an external file system with filenames saved in BSON)

The first point could be implemented very easily, but `tolist` remains the more readable solution. So, it would be worth making using `tostring` optional somehow. As the name suggests, this returns a string, which is acceptable in JSON

The second point is less important, but may help avoid having to deal with the third point immediately. Using `blosc` is relatively straightforward, there are already nice Python bindings for this ( https://github.com/ContinuumIO/python-blosc ). The benchmarking included already shows how simple this is to do. It is worth noting that `blosc` is very fast and is designed for frequent transmission. This returns a string, which is acceptable in JSON.

The third point may take more or less work depending on the strategy chosen. An easy way to solve this would be to use HDF5 outside of MongoDB and simply store the filenames with dataset in the MongoDB documents. HDF5 has its own ways to do compression, but third party compression strategies can be used, as well. Here `h5py` is probably the best way to go if HDF5 is selected. The alternative could be using GridFS (compression would be tricky). Being able to adjust block sizes would be nice if GridFS is selected.

**Comment by shyuep** [comment]
That's not really the purpose of monty's serialization. The serialization in monty returns a dict form that is json compatible. That also allows insertion into MongoDB. Using binary formats like HDF5 would of course be more efficient, but it makes it difficult to query.

**Comment by jakirkham** [comment]
However, the first two points do return strings that are JSON compatible could we at least provide them some consideration.

**Comment by shyuep** [comment]
The whole idea is not to have a string that cannot be queried.
I acknowledge that we can always have more efficient options. But the design is meant for insertion into NoSQL databases and for querying. Serialization is a secondary important objective, but it is not the overriding one in terms of efficiency.

**Comment by jakirkham** [comment]
> The whole idea is not to have a string that cannot be queried.

I don't follow this. The dictionary as you see it will still be intact. All I am suggesting is that the data optionally (by some user controlled parameter) can be the byte representation of the array compressed or otherwise.

> But the design is meant for insertion into NoSQL databases and for querying.

Again the first two options provide a string. I don't understand the problem.

**Comment by wmdrichards** [comment]
fyi, its possible to save numpy arrays (in their binary format) directly to
GridFS using something similar to the following:

with TemporaryFile() as t:
        np.save(t, array)
        t.seek(0)
        _id = gridfs.GridFS(db, collection).put(t)

and then you can reload with np.load()

Will
