### ISSUE TITLE
Support for UUID objects

### ISSUE THREAD

**Issue by utf** [materialsvirtuallab/monty#219]
Hi @shyuep 

Would you accept a PR adding support for serialising UUID objects in `MontyEncoder`? These objects have been part of the Python standard library since Python 2.7, so there wouldn't be any additional dependencies. 

If so I will submit one shortly.

**Comment by shyuep** [comment]
Sure of course. Just make sure it is backwards compatible and does not cause issues with existing code.
In general, adding support for new data types is perfectly fine.
