### ISSUE TITLE
Python version support

### ISSUE THREAD

**Issue by ajjackson** [materialsvirtuallab/monty#249]
When reporting bugs/issues, please supply the following information. If this 
is a feature request, please simply state the requested feature.

## System

* Monty version: 2021.3.3
* Python version: 3.4
* OS version: Fedora 33

## Summary

* Monty documentation consistently says that all Python 3.x versions are supported
* The most recent release 2021.3.3 only supports Python 3.5 and above (setup.py metadata)

Is this an oversight or is Monty officially dropping support for older Python versions?

**Comment by shyuep** [comment]
We are dripping support for older python versions.
