### ISSUE TITLE
Problem with yaml serialization in dumpfn/loadfn

### ISSUE THREAD

**Issue by shyamd** [materialsvirtuallab/monty#36]
Right now dumpfn and loadfn can take msonable objects and dump/load to json.  It appears this not possible with yaml objects. It appears as if ruamel/yaml is not being informed of the MSONable pattern by being given a MontyEncoder or MontyDecoder. I don't know if this is possible.

**Comment by shyuep** [comment]
yaml dumps do not take in an encoder and decoder. So this is not possible. There are workarounds, but I would generally avoid it. Yaml is supposed to support serialization of arbitrary classes
