### ISSUE TITLE
Thoughts on adding `@version` to MSONable?

### ISSUE THREAD

**Issue by mkhorton** [materialsvirtuallab/monty#41]
When considering the upcoming v3 of the MP API, @shyamd and I were discussing data integrity and in particular we're using an "implicit schema" with MSONable serialized objects.

What we're currently lacking is version information so that if a backwards-incompatible changes is made to object serialization/de-serialization, we can not tell from the database alone whether a serialized object will be compatible or not.

Proposal is to add `@version` in addition to `@module` and `@class` and, by default, this would include the output of `module.__version__`.

**Comment by shyuep** [comment]
No problem

**Comment by mkhorton** [comment]
Great, will implement
