### ISSUE TITLE
Tarball 2022.9.9 has not all tests files

### ISSUE THREAD

**Issue by eamanu** [materialsvirtuallab/monty#442]
Hi, 

During the packaging of monty 2022.9.9 in Debian I can note that the tests fails 
because they are looking for not existing files.

Also, you can see that CI is failed for that reason [0]. Do you have any plan
for a soon new release fixing that?

[0] https://github.com/materialsvirtuallab/monty/tree/v2022.9.9

Thanks!
Cheers,

**Comment by shyuep** [comment]
Test files are not meant to be included in the tarball. The tarball is meant for users. For developers needing the test files, it is better to fork and clone the repo.
