### ISSUE TITLE
`tests` directory is wrongly packaged into the wheel

### ISSUE THREAD

**Issue by njzjz** [materialsvirtuallab/monty#469]
When reporting bugs/issues, please supply the following information. If this
is a feature request, please simply state the requested feature.

## System

* Monty version:  2022.9.9 
* Python version: 3.7
* OS version: linux

## Summary

* `tests` directory is wrongly packaged into the wheel and installed to `<python directory>/lib/python3.x/site-packages/tests`.

## Example code

```sh
wget https://files.pythonhosted.org/packages/b3/39/bcb570d7214a083f8810b55af97b124b77be8431268e09a5f78fa0c9a383/monty-2022.9.9-py3-none-any.whl
unzip monty-2022.9.9-py3-none-any.whl
ls tests/
```

**Comment by shyuep** [comment]
This is a well-known bug in wheel generation that does not respect the recursive-exclude command. Unfortunately this is a Python tool issue and I don't really have a solution. I don't think the inclusion of test files is causing any problem though?

**Comment by njzjz** [comment]
https://github.com/pypa/wheel/issues/99#issuecomment-317885403

This should work when `tests` is not passed to `setup(packages=...)`.
