### ISSUE TITLE
Various functions are not safe to use with `pathlib.Path` objects (only `str`)

### ISSUE THREAD

**Issue by arosen93** [materialsvirtuallab/monty#550]
Several of the functions in monty are not safe to use with `pathlib.Path` objects as the input. This is not a bug since the type-hint or docstring indicates it's just `str`, but it's worth updating at some point.

For instance, take the example below:

https://github.com/materialsvirtuallab/monty/blob/ae7f481a8519b87499e9a09b01ba1df4026ee361/monty/shutil.py#L96-L107

Calling `.split()` on a `Path` object isn't possible.

For maximum flexibility, a simple enhancement would be to call `str(<input>)` at the top of the various path handling functions, which would then allow the input type to be either `str` or `Path`.

**Comment by shyuep** [comment]
I would go the opposite route. Convert all str to Paths and use the proper Path operations.

**Comment by arosen93** [comment]
@shyuep: Noted. I took the easy way out in #551. I'll stop being lazy... :)

**Comment by shyuep** [comment]
Note that Path(obj) works no matter what. Even if the user has already provided a path.
