### ISSUE TITLE
[Feature Request]: `compress_file` and `decompress_file` allow specify target path

### ISSUE THREAD

**Issue by DanielYang59** [materialsvirtuallab/monty#632]
### Problem

Would it be a good idea to allow user to optionally specific the output file path for `compress_file` and `decompress_file`?  I could help implement this if so.

Or is there any reason not to do so? 

Thanks

### Proposed Solution

Append a prefix to `filepath` (if not None) should suffice:
https://github.com/materialsvirtuallab/monty/blob/4d60fd4745f840354e7b3f48346eaf3cd68f2b35/monty/shutil.py#L79-L87

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Andrew-S-Rosen** [comment]
I think this would make sense. The same goes for `decompress_dir`. 

Right now, I basically always `copy_r` and then `decompress_dir` (or `copy` then `decompress_file`). Adding an option for a target path would condense each of those into one step.

**Comment by DanielYang59** [comment]
Thanks for the reponse. I would go ahead and implement this 😃 .
