### ISSUE TITLE
[Feature Request]: pickle fallback for un-MSONable class properties

### ISSUE THREAD

**Issue by matthewcarbone** [materialsvirtuallab/monty#653]
### Email (Optional)

Preference for just @matthewcarbone in this issue.

### Problem

`monty.json.MSONable` is one of my favorite mixins, and it allows for seamless serialization of classes. However, there are often instances in which classes are unserializable to json due to including attributes that themselves are not serializable, and do not have a defined protocol for serialization in `monty.json`. Obviously, pickling classes directly comes with its drawbacks, but I have an idea.

### Proposed Solution

A new mixin class (we'll call it MSONable2) which defines the `save` and `load` methods. For classes that are completely MSONable, these methods fallback directly on using the json encoder, and saving/loading a json file to the provided path.

However, for classes which are not entirely serializable, for each attribute that isn't, the methods fallback on pickle to save just those objects, one at a time, into a provided directory. This will result in a partially saved json file. I think my idea here is best demonstrated by example.

```python
class TestClass(MSONable2):
	p1 = 123
	p2 = {"hi": "there"}
	p3 = [1, 2, 3, "5"]
	p4 = torch.optimizers.Adam(model.parameters())
```

Above, clearly `p4` is not json-serializable. The way this would work is something like this:

```python
klass = TestClass()
klass.save("path/to/directory/klass.json")
```

Resulting in a json file that looks like this:

```json
{
	"@module": "my.module",
	"@version": "1.2.3",
	"@class": "TestClass",
	"p1": "123",
	"p2": "...",
	"p3": "...",
	"p4": "path/to/directory/klass.pkl",
	"_PICKLE_SERIALIZED_": "p4",
}
```

I'm being lazy with `p2` and `p3`, but you get the idea.

Loading would similarly understand which variables need to be reinstantiated from the pickled data, and which could be loaded normally. Warnings can also be thrown if versions don't match during load.

I can't even begin to explain how useful this would be to me personally, so I imagine others will feel the same way.

### Alternatives

I'm not sure. My alternative is coding it up myself and releasing my own package, but it really feels like this belongs in monty. Happy to do it on my own if you feel it's out of scope though.

Only other alternative is to define more ways of serializing currently unserializable classes.

**I should note I am happy to implement these changes and open a PR.**

@shyuep I see you're making changes to the code recently, what do you think?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shyuep** [comment]
This suggestion is fine with me. But I would not bother with a MSONAble2. You can simply modify MSONAble to support this. In other words, MSONAble will use json where possible and fall back on pickle when it cannot.

**Comment by matthewcarbone** [comment]
@Andrew-S-Rosen can we reopen this and close #659 (which should be resolved in the recent rollback)? I'll attempt to fix the issues from before and we can more thoroughly test it this time before merging.

**Comment by Andrew-S-Rosen** [comment]
I don't have permissions to reopen a PR, but I closed the linked issue.

**Comment by matthewcarbone** [comment]
No worries. My plan is to open up a new PR once I have something more complete. We can either leave this closed or not, doesn't matter too much.

Current idea is as follows:
- Leave the decoder alone completely
- Keep the modifications to the encoder I had in #654 
- Upon loading the saved json file, recursively search through it, replacing all `@object_reference` keys with the objects themselves, then pass that to that class's `from_dict`

Let me know what you think if you have the time. Either way we can discuss later when I open a PR.

**Comment by matthewcarbone** [comment]
@Andrew-S-Rosen I've created a modified version of this idea, which you can find [here](https://github.com/matthewcarbone/ScientificValueAgent/blob/0467e837aa880cd14fd16a1ccfafa880bdecc55d/sva/monty/json.py#L439). I've hosted a copy of `monty.json` for now (under the terms of Monty's license) to stress test the method with my own code. It seems to be working. I have left the decoder alone completely, and the encoder has been slightly modified to fallback on this pickling strategy only when other methods fail.

For extra safety, I would actually still recommend something similar to what I did before: I can just make a `monty.json2` module, copy/paste the necessary ingredients over such that `monty.json` is left completely alone. Is this redundant, janky and bad practice overall? Absolutely. But given the cascade of failures my previous bug ended up causing, I think it's safer to do it this way for now. If the code ends up being stable and we feel comfortable, we can integrate it later.

If there's still enough interest in this idea, I can open a new PR! What do you think?
