### ISSUE TITLE
[Bug]: The `MSONAtoms` class does not rehydrate from `loadfn`

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsvirtuallab/monty#659]
### Version

b887f02

### Which OS(es) are you using?

- [x] MacOS
- [x] Windows
- [x] Linux

### What happened?

The recently introduced `pymatgen.io.ase.MSONAtoms` class does not properly "rehydrate" from a JSON file via monty's `loadfn` utility even though `MSONAtoms.from_dict()` works appropriately.

#### Setup

```bash
pip install git+https://github.com/materialsvirtuallab/monty.git pymatgen ase
```

#### Example that fails

```python
from monty.serialization import loadfn

loadfn("test.json")
```

[test.json](https://github.com/materialsproject/pymatgen/files/15001117/test.json)

### Log output

```shell
--------------------------------------------------------------------------
TypeError                                Traceback (most recent call last)
Cell In[2], line 1
----> 1 loadfn("test.json")

File c:\Users\asros\miniconda\envs\test\Lib\site-packages\monty\serialization.py:82, in loadfn(fn, fmt, *args, **kwargs)
     80     if "cls" not in kwargs:
     81         kwargs["cls"] = MontyDecoder
---> 82     return json.load(fp, *args, **kwargs)
     84 raise TypeError(f"Invalid format: {fmt}")

File c:\Users\asros\miniconda\envs\test\Lib\json\__init__.py:293, in load(fp, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    274 def load(fp, *, cls=None, object_hook=None, parse_float=None,
    275         parse_int=None, parse_constant=None, object_pairs_hook=None, **kw):
    276     """Deserialize ``fp`` (a ``.read()``-supporting file-like object containing
    277     a JSON document) to a Python object.
    278 
   (...)
    291     kwarg; otherwise ``JSONDecoder`` is used.
    292     """
--> 293     return loads(fp.read(),
    294         cls=cls, object_hook=object_hook,
    295         parse_float=parse_float, parse_int=parse_int,
    296         parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)

File c:\Users\asros\miniconda\envs\test\Lib\json\__init__.py:359, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    357 if parse_constant is not None:
    358     kw['parse_constant'] = parse_constant
--> 359 return cls(**kw).decode(s)

File c:\Users\asros\miniconda\envs\test\Lib\site-packages\monty\json.py:796, in MontyDecoder.decode(self, s)
    794 else:
    795     _d = json.loads(s)
--> 796 return self.process_decoded(_d)

File c:\Users\asros\miniconda\envs\test\Lib\site-packages\monty\json.py:770, in MontyDecoder.process_decoded(self, d)
    763         elif (
    764             (bson is not None)
    765             and modname == "bson.objectid"
    766             and classname == "ObjectId"
    767         ):
    768             return bson.objectid.ObjectId(d["oid"])
--> 770     return {
    771         self.process_decoded(k): self.process_decoded(v) for k, v in d.items()
    772     }
    774 if isinstance(d, list):
    775     return [self.process_decoded(x) for x in d]

File c:\Users\asros\miniconda\envs\test\Lib\site-packages\monty\json.py:771, in <dictcomp>(.0)
    763         elif (
    764             (bson is not None)
    765             and modname == "bson.objectid"
    766             and classname == "ObjectId"
    767         ):
    768             return bson.objectid.ObjectId(d["oid"])
    770     return {
--> 771         self.process_decoded(k): self.process_decoded(v) for k, v in d.items()
    772     }
    774 if isinstance(d, list):
    775     return [self.process_decoded(x) for x in d]

File c:\Users\asros\miniconda\envs\test\Lib\site-packages\monty\json.py:716, in MontyDecoder.process_decoded(self, d)
    713 data = {k: v for k, v in d.items() if not k.startswith("@")}
    714 if hasattr(cls_, "_from_dict"):
    715     # New functionality with save/load requires this
--> 716     return cls_._from_dict(
    717         data, name_object_map=self._name_object_map
    718     )
    719 if hasattr(cls_, "from_dict"):
    720     return cls_.from_dict(data)

File c:\Users\asros\miniconda\envs\test\Lib\site-packages\monty\json.py:247, in MSONable._from_dict(cls, d, name_object_map)
    244 @classmethod
    245 def _from_dict(cls, d, name_object_map):
    246     decoded = MSONable.decoded_from_dict(d, name_object_map=name_object_map)
--> 247     return cls(**decoded)

TypeError: Atoms.__init__() got an unexpected keyword argument 'atoms_json'
```

### Note

The following *does* work.

```python
from pymatgen.io.ase import MSONAtoms

d = {"test": {"@module": "pymatgen.io.ase", "@class": "MSONAtoms", "atoms_json": "{\"numbers\": {\"__ndarray__\": [[16], \"int32\", [11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 46, 46, 46, 46]]}, \"positions\": {\"__ndarray__\": [[16, 3], \"float64\", [1.8079, 5.42368, 5.42369, 1.8079, 1.8079, 5.42368, 3.61579, 0.0, 0.0, 1.8079, 1.8079, 1.8079, 1.8079, 5.42368, 1.8079, 3.61579, 3.61579, 3.61579, 5.42369, 5.42368, 1.8079, 5.42369, 1.8079, 1.8079, 0.0, 0.0, 3.61579, 5.42369, 1.8079, 5.42369, 5.42369, 5.42368, 5.42369, 0.0, 3.61579, 0.0, 0.0, 0.0, 0.0, 0.0, 3.61579, 3.61579, 3.61579, 0.0, 3.61579, 3.61579, 3.61579, 0.0]]}, \"cell\": {\"__ndarray__\": [[3, 3], \"float64\", [7.23158, 0.0, 0.0, 0.0, 7.23158, 0.0, 0.0, 0.0, 7.23158]]}, \"pbc\": {\"__ndarray__\": [[3], \"bool\", [true, true, true]]}, \"__ase_objtype__\": \"atoms\"}", "atoms_info": {"_id": "d60ac0ad306752f82cf823fac70f2bbd"}}}

MSONAtoms.from_dict(d["test"])
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shyuep** [comment]
Must be a 3 body problem.

**Comment by Andrew-S-Rosen** [comment]
After lots of painful digging, I have identified that the source of the problem with `loadfn` can be traced back to https://github.com/materialsvirtuallab/monty/pull/654 by @matthewcarbone.

@matthewcarbone: do you have any insights here on why the PR would break `loadfn` behavior?

**Comment by matthewcarbone** [comment]
@Andrew-S-Rosen not precisely sure what's wrong here, but clearly the saved state is not getting unwrapped correctly, since by the time `Atoms.__init__` is called, `atoms_json` should've been accessed already such that `Atoms` has access to `atoms_info`...

I mean, silly question, does this work with a version of monty prior to my PR? `_from_dict` is just meant to be a passthrough to maintain all previous behavior. I can also look into this but let me know what you think.

I'm also happy to roll back my additions and put them in a `MSONable2` class (suggested in my PR) to avoid some of these possible pitfalls in the future.

**Comment by Andrew-S-Rosen** [comment]
I'll reply more in a bit, but yup I confirmed it works on the commit immediately preceding your PR. 👍

**Comment by matthewcarbone** [comment]
Yeah I did too. I'm gonna fix it, or at least figure out what's wrong. I'll update as I go along.

**Comment by matthewcarbone** [comment]
Ah, I think I got it. It's because `_from_dict` is inherited from `MSONable` directly, whereas `MSONAtoms` overwrites it: https://github.com/materialsproject/pymatgen/blob/0e57abf35d620f5c09149d72ba12493184135611/pymatgen/io/ase.py#L69. 

Can you confirm? This is an easy fix. I probably just need to redefine the logic in `MSONable` to just use `from_dict`.

**Comment by Andrew-S-Rosen** [comment]
Ah, that does indeed seem like it! Good catch!

**Comment by Andrew-S-Rosen** [comment]
@matthewcarbone: I can confirm that commenting out the line below related to `_from_dict` "resolves" the issue in this case.

https://github.com/materialsvirtuallab/monty/blob/996108f37bb4e2bfbf7a323a535769c3e017321d/monty/json.py#L714-L718

**Comment by matthewcarbone** [comment]
@Andrew-S-Rosen I think I have an idea of how to fix this. I think I'll just completely remove those lines attempt to bake in the logic outside of `from_dict`, that way people can safely override that method without affecting the `save`/`load` functionality. Thoughts?

**Comment by Andrew-S-Rosen** [comment]
If you think that might be possible, then that would be a huge help! It makes sense to me.

I appreciate you taking a look at this. I understand it's somewhat of an unusual scenario that wasn't caught by the test suite.

**Comment by matthewcarbone** [comment]
@Andrew-S-Rosen I think it should be possible. Are you familiar with what my PR did? I'll summarize quickly so you have background on it just in case.

Basically, any time the encoder encounters an object it cannot serialize using MSONable, it swaps that object in the dictionary with a hash, and creates a new dictionary (`name_object_map`) which maps that hash to the object. That second dictionary is pickled next to the json file. So, `save` basically serializes in human-readable format "as much as possible", falling back on pickle for the rest.

My approach to fixing this issue will be to remove all of the deserialization logic from `from_dict`. Instead, recursively searching through and replacing any of these hashes (which start with the key `@object_reference`) in the `load` function.

Clearly we have to keep `from_dict` as it was before to ensure compatibility with classes that overwrite it. Do you agree?

**Comment by Andrew-S-Rosen** [comment]
@matthewcarbone: Thanks for the explanation. I fully agree with your logic. (Also, I think the pickle save fallback was a very nice idea).

**Comment by matthewcarbone** [comment]
@Andrew-S-Rosen sounds good. Sorry for introducing a new bug (which appears to have made it's way into other repositories somehow). Given that this issue seems to be impacting other repos might I suggest either version-locking those repositories to a bug-free version of monty or hotfixing the current version of monty (rolling back my feature until I can get it polished)?
