### ISSUE TITLE
Why the version from github repo tag `v2024.7.29` differs from PyPI `2024.7.30`?

### ISSUE THREAD

**Issue by DanielYang59** [materialsvirtuallab/monty#718]
Why the version from github repo tag `v2024.7.29` differs from PyPI `2024.7.30`? Timezone issue maybe?

It's very confusing: https://github.com/materialsproject/pymatgen/blob/aa37e99fa67a0e9f996b645be26c12a8f42a4a98/pyproject.toml#L59

<img width="607" alt="image" src="https://github.com/user-attachments/assets/f767cee0-3b7f-4c4a-99c5-cf6c1b580d87">

<img width="607" alt="image" src="https://github.com/user-attachments/assets/849958ef-171b-45cb-bb26-744f6365e6db">

**Comment by shyuep** [comment]
Since a new version has been released, I will close this.

**Comment by DanielYang59** [comment]
Thanks for pushing a new release, I thought we should be able edit the tag from GitHub from the below button in "releases" in case someone else need `2024.7.30` for whatever reason  (but not pypi)? I could be wrong here.

<img width="145" alt="image" src="https://github.com/user-attachments/assets/c0b26f39-c837-4546-99d6-354907603133">

**Comment by shyuep** [comment]
We can, but it is probably not relevant since there has been a new version since....

**Comment by DanielYang59** [comment]
Okay thanks! (was saying this in case someone might need `2024.7.30` for whatever reason)

Thanks again for pushing a new release, that really helps!
