### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by vivianshangg** [materialsvirtuallab/monty#723]
### Version

2024.10.21

### Which OS(es) are you using?

- [X] MacOS
- [ ] Windows
- [ ] Linux

### What happened?

running python3.9 ..... we get.... 
monty 2024.10.21 requires numpy<2.0.0, but you have numpy 2.0.1 which is incompatible.

can we please have support for numpy 2?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shyuep** [comment]
monty does not require numpy at all. Numpy is an optional dependency. I am pretty sure it will work with any numpy version.
